# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ed24f11c8d5d66ac4ca26504e457401a0220ea57f37e32eec57a5a1e444dd1ca8dea8b0400acce73224323696a7a508ca2dd6fdc95d9f615a0d8e7380491ccf

test:
  secret_key_base: 01ff74b827ba943942c1732e4d4393e2d126bdebdebe5382087d475638cf86dbdfa21e47baed151305248fad8f1e6d2e59f332dea1049b8b048c7dd69947f5fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
